name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-add-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: ls
      run: ls
    
    - name: cmake
      run: cmake .
      
    - name: make
      run: make
      
    - name: test
      run: ./bin/test_Polynom
      

